services:
    postgres:
        image: postgres
        container_name: galhardo-app-db
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql
        networks:
            - network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: galhardo-app-rabbitmq
        restart: always
        environment:
            - "RABBITMQ_DEFAULT_PASS=rabbitmq"
            - "RABBITMQ_DEFAULT_USER=rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    postgres:
        driver: local
